### ISSUE TITLE
Provide Screenshoot in Readme.md

### ISSUE THREAD

**Issue by rasyidf** [fahminlb33/Moviebase#1]
the readme.md seems too simple, and don't get the functionality, add screenshoot to it to Hype others.

**Comment by fahminlb33** [comment]
This project is very old, I've just managed to make it work again by implementing more updated APIs.
For more description, you could visit this forum post: https://www.kaskus.co.id/thread/593f6264d675d48e4a8b4567/moviebase-aplikasi-untuk-organisir-film-agan

I'll soon rework the readme file, do you interested to contribute more to this project? I'm planning to use WPF instead of WinForms.

**Comment by fahminlb33** [comment]
fixed it.
